apiVersion: v1
kind: Secret
metadata:
  name: omgwtfssl
  namespace: default
type: kubernetes.io/tls
data:
  tls.key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  tls.crt: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
